spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/sb_23_11_27_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:./sb_23_11_27_test;MODE=MySQL
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:
  jpa:
    hibernate:
      ddl-auto: create